### ISSUE TITLE
Path to the "lsp" directory in GNU/Linux

### ISSUE THREAD

**Issue by negora** [Chris2011/netbeans-textmate-files#2]
Hi:

I've seen that the path to the `lsp` directory in GNU/Linux is still to be determined. I'm referring to the https://github.com/Chris2011/netbeans-textmate-files/blob/master/README.md file.

Well, the path should be like this:
```
$HOME/.netbeans/YourNetBeansVersion/config/Preferences/org/netbeans/modules/lsp/
```

By the way, thank you for helping us to configure our NetBeans instances for LSP. Although I've almost moved to another IDE, I'm still withstanding to abandon NetBeans (17 years using it and still love it).

Salutes.

**Comment by Chris2011** [comment]
Hey @negora thx for pointing me to the Linux link. Will change the Readme asap :). Great to hear, that you are still working with NetBeans. But btw this repo is just for the grammar, not for LSP. Maybe later, If I have all possible LS for each language, I will try to add them too. But I think this is not that much standarized.

I do my best, what I can to contribute to NetBeans but unfortunately time and knowledge of all that stuff is limited. I'm just a frontend webdeveloper who has other profession and this is not Java and not Swing. The rest is unterstanding the API and the NetBeans stuff how it was build etc.

Cheers

Chris

**Comment by negora** [comment]
@Chris2011

> But btw this repo is just for the grammar, not for LSP. Maybe later, If I have all possible LS for each language, I will try to add them too. But I think this is not that much standarized.

Do you mean to include the binaries of that servers or just references to their respective projects? If it's the former, I guess that the matter of the licenses will make it hard to redistribute every existing LSP server.

> I do my best, what I can to contribute to NetBeans but unfortunately time and knowledge of all that stuff is limited. I'm just a frontend webdeveloper who has other profession and this is not Java and not Swing. The rest is unterstanding the API and the NetBeans stuff how it was build etc.

We talked to each other time ago, in the *Issues* section of the [Everlaw/nbts](https://github.com/Everlaw/nbts) repository. And you reminded myself in some aspects: we would love contributing to NetBeans, but we've no time to do so. In my case I'm a Java developer, but focused on the back-end (for the front-end I always used Web technologies). So I should have to start from scratch with Swing and all that stuff.

Thank you for your sharing your contributions to NetBeans.

**Comment by Chris2011** [comment]
Including the binaries, yes. But I think not everyone will work the same I guess. But will check one day.

For other dialogs, please come and join the slack chan, so we can talk deeper if you want :)

**Comment by negora** [comment]
@Chris2011 

>For other dialogs, please come and join the slack chan, so we can talk deeper if you want :)

My English is not very fluent and I've almost no free time nowadays, but one day I'd like to check that channel. Thank you for the invitation ;) .

**Comment by akronenw** [comment]
Hi, 

I will just drop my info in this topic; the path to the `lsp` directory in macOS is
`$HOME/Library/Application Support/NetBeans/YourNetBeansVersion/config/Preferences/org/netbeans/modules/lsp`.

It works well, thanks!

**Comment by Chris2011** [comment]
Hey @akronenw thx will add it to the readme asap :).

**Comment by Chris2011** [comment]
Thx for helping me out with the paths, I added it just now to the readme.
